In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from scipy.stats.stats import pearsonr
import scipy.optimize as optimize
import math
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn import linear_model
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn import neighbors
import seaborn as sns
from math import sqrt
from sklearn.metrics import mean_absolute_error, mean_squared_error, explained_variance_score, r2_score

df_tran = pd.read_csv('../dataset/tran.txt',names=['primary-date','time','approximate-indicator','secondary-date','approximate-indicator',
  'transaction-ID','player','type','from-team','from-league','to-team','to-league','draft-type','draft-round','pick-number','info'])
df_playerid = pd.read_csv('../dataset/playerid_list.csv',names=['LASTNAME','FIRSTNAME','PLAYERID','DAVENPORTCODE','MLBCODE','player'],skiprows=1);
df_master = pd.read_csv('../dataset/Master.csv')
df_batting = pd.read_csv('../dataset/Batting.csv')
df_pitching = pd.read_csv('../dataset/Pitching.csv')
df_fielding = pd.read_csv('../dataset/Fielding.csv')
df_batstat = pd.read_csv('../dataset/war_daily_bat.txt')
df_pitchstat = pd.read_csv('../dataset/war_daily_pitch.txt')
df_cpi = pd.read_csv('../dataset/CPI.csv')
df_salaries = pd.read_csv('../dataset/Salaries.csv')
pd.set_option('display.max_columns', 60)
df_teams = pd.read_csv('../dataset/Teams.csv')

# Data Cleanup
# Recontructing invalid dates
df_tran['primary-date'] = df_tran['primary-date'].astype('str')
df_tran['primary-date'] = df_tran['primary-date'].str.replace(r'\A(\d{4})[0]{4}', r'\g<1>0101')
df_tran['primary-date'] = df_tran['primary-date'].str.replace(r'\A(\d{4})(..)[0]{2}', r'\g<1>\g<2>01')

#Extracting only trades from transaction dataframe
df_tran = df_tran[df_tran['type'] == "T "]
df_tran = df_tran[df_tran['to-league'].isin(['AL','NL'])]
df_tran = df_tran[df_tran['from-league'].isin(['AL','NL'])]

df_tran['primary-date'] = pd.to_datetime(df_tran['primary-date'], format='%Y%m%d')
df_tran['tranYear'] = df_tran['primary-date'].apply(lambda x : int(x.year))

C:\Users\ANKIT\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:2723: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [2]:
df_manager = pd.read_csv('../dataset/Managers.csv')

In [3]:
df_manager= df_manager.sort( ['playerID','yearID'] )
playerID= ''
yearID= ''
win = 0
loss= 0
Game= 0
for i, row in df_manager.iterrows():
    if playerID == row['playerID']:
        loss = row['L'] + loss
        win = row['W'] + win
        Game = row['G'] + Game
        df_manager['W'][i] = win;
        df_manager['L'][i] = loss;
        df_manager['G'][i] = Game;
        
    else:
        playerID= row['playerID']
        yearID= row['yearID']
        win = row['W']
        loss = row['L']
        Game = row['G']

C:\Users\ANKIT\Anaconda\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':
C:\Users\ANKIT\Anaconda\lib\site-packages\ipykernel\__main__.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\ANKIT\Anaconda\lib\site-packages\ipykernel\__main__.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\ANKIT\Anaconda\lib\site-packages\ipykernel\__main__.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [4]:
df_manager

       playerID  yearID teamID lgID  inseason     G     W     L  rank plyrMgr
3132   actama99    2007    WAS   NL         1   162    73    89   4.0       N
3166   actama99    2008    WAS   NL         1   323   132   191   5.0       N
3199   actama99    2009    WAS   NL         1   410   158   252   5.0       N
3206   actama99    2010    CLE   AL         1   572   227   345   4.0       N
3242   actama99    2011    CLE   AL         1   734   307   427   2.0       N
3277   actama99    2012    CLE   AL         1   890   372   518   5.0       N
1910  adairbi99    1970    CHA   AL         2    10     4     6   6.0       N
1827  adcocjo01    1967    CLE   AL         1   162    75    87   8.0       N
61     addybo01    1875    PH2  NaN         2     7     3     4   5.0       Y
79     addybo01    1877    CN1   NL         2    31     8    23   6.0       Y
347   allenbo01    1890    PHI   NL         4    35    25    10   3.0       Y
523   allenbo01    1900    CIN   NL         1   179    87    87   7.0       Y
31    allisdo01    1873    ELI  NaN         1    23     2    21   8.0       N
3278  alomasa02    2012    CLE   AL         2     6     3     3   5.0       N
2635   aloufe01    1992    MON   NL         2   125    70    55   2.0       N
2665   aloufe01    1993    MON   NL         1   287   164   123   2.0       N
2695   aloufe01    1994    MON   NL         1   401   238   163   1.0       N
2724   aloufe01    1995    MON   NL         1   545   304   241   5.0       N
2758   aloufe01    1996    MON   NL         1   707   392   315   2.0       N
2790   aloufe01    1997    MON   NL         1   869   470   399   4.0       N
2822   aloufe01    1998    MON   NL         1  1031   535   496   4.0       N
2856   aloufe01    1999    MON   NL         1  1193   603   590   4.0       N
2886   aloufe01    2000    MON   NL         1  1355   670   685   4.0       N
2920   aloufe01    2001    MON   NL         1  1408   691   717   5.0       N
2998   aloufe01    2003    SFN   NL         1  1569   791   778   1.0       N
3032   aloufe01    2004    SFN   NL         1  1731   882   849   2.0       N
3066   aloufe01    2005    SFN   NL         1  1893   957   936   3.0       N
3096   aloufe01    2006    SFN   NL         1  2054  1033  1021   3.0       N
1536  alstowa01    1954    BRO   NL         1   154    92    62   2.0       N
1553  alstowa01    1955    BRO   NL         1   308   190   117   1.0       N
...         ...     ...    ...  ...       ...   ...   ...   ...   ...     ...
2992   yostne01    2003    MIL   NL         1   162    68    94   6.0       N
3025   yostne01    2004    MIL   NL         1   323   135   188   6.0       N
3060   yostne01    2005    MIL   NL         1   485   216   269   3.0       N
3091   yostne01    2006    MIL   NL         1   647   291   356   4.0       N
3125   yostne01    2007    MIL   NL         1   809   374   435   2.0       N
3157   yostne01    2008    MIL   NL         1   959   457   502   2.0       N
3209   yostne01    2010    KCA   AL         2  1086   512   574   5.0       N
3244   yostne01    2011    KCA   AL         1  1248   583   665   4.0       N
3280   yostne01    2012    KCA   AL         1  1410   655   755   NaN       N
3311   yostne01    2013    KCA   AL         1  1572   741   831   3.0       N
3350   yostne01    2014    KCA   AL         1  1734   830   904   2.0       N
3376   yostne01    2015    KCA   AL         1  1896   925   971   1.0       N
640   youngcy01    1907    BOS   AL         1     6     3     3   7.0       Y
10    youngni99    1871    WS3  NaN         1    32    15    15   4.0       N
24    youngni99    1872    WS3  NaN         1    41    17    22   8.0       N
37    youngni99    1873    WS5  NaN         1    80    25    53   7.0       N
580   zimmech01    1903    PHI   NL         1   139    49    86   7.0       Y
1989  zimmedo01    1972    SDN   NL         2   142    54    88   6.0       N
2018  zimmedo01    1973    SDN   NL         1   304   114   190   6.0       N
2083  zimmedo01    1976    BOS   AL         2   380   156   224   3.0       N
2110  zimmedo01    1977    BOS   AL         1   541   253   288   3.0       N
2148  zimmedo01    1978    BOS   AL         1   704   352   352   2.0       N
2182  zimmedo01    1979    BOS   AL         1   864   443   421   3.0       N
2216  zimmedo01    1980    BOS   AL         1  1019   525   494   4.0       N
2267  zimmedo01    1981    TEX   AL         1  1124   582   542   2.0       N
2297  zimmedo01    1982    TEX   AL         1  1220   620   600   6.0       N
2497  zimmedo01    1988    CHN   NL         1  1383   697   685   4.0       N
2530  zimmedo01    1989    CHN   NL         1  1545   790   754   1.0       N
2559  zimmedo01    1990    CHN   NL         1  1707   867   839   5.0       N
2596  zimmedo01    1991    CHN   NL         1  1744   885   858   4.0       N

[3405 rows x 10 columns]

In [19]:
manager_df = pd.DataFrame(columns = ['tran_ID','tran_Year','Team1','Team1_mgr','Team1_mgr_score','Team2','Team2_mgr','Team2_mgr_score'])
df_sort = df_tran.sort(['transaction-ID'])
td = df_sort['transaction-ID'].unique()
manager_df['tran_ID'] = td
for i,row in manager_df.iterrows():
    tran_id = df_sort[df_sort['transaction-ID']==row['tran_ID']].iloc[0]
    manager_df['tran_Year'][i] = tran_id['tranYear']
    manager_df['Team1'][i] = tran_id['from-team']
    manager_df['Team2'][i] = tran_id['to-team']
    mgr_table1 = df_manager[df_manager['yearID'] == tran_id['tranYear']]
    mgr_table = mgr_table1[mgr_table1['teamID'] == tran_id['from-team']]
     #mgr_table = df_manager[mgr_table1 & mgr_table2
    
    if mgr_table.empty:
        print 'empty'
    else:
        manager_df['Team1_mgr'][i] = mgr_table['playerID'].iloc[0];
        manager_df['Team1_mgr_score'][i] = mgr_table['W'].iloc[0]-mgr_table['L'].iloc[0];
    
    #mgr_table1 = df_manager['yearID'] == tran_id['tranYear']
    mgr_table = mgr_table1[mgr_table1['teamID'] == tran_id['to-team']]
      #mgr_table = df_manager[mgr_table1 & mgr_table2]
    if mgr_table.empty:
        print 'empty'
    else:
        manager_df['Team2_mgr'][i] = mgr_table['playerID'].iloc[0];
        manager_df['Team2_mgr_score'][i] = mgr_table['W'].iloc[0]-mgr_table['L'].iloc[0];

C:\Users\ANKIT\Anaconda\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from ipykernel import kernelapp as app
C:\Users\ANKIT\Anaconda\lib\site-packages\ipykernel\__main__.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\ANKIT\Anaconda\lib\site-packages\ipykernel\__main__.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\ANKIT\Anaconda\lib\site-packages\ipykernel\__main__.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\ANKIT\Anaconda\lib\site-packages\ipykernel\__main__.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

empty

C:\Users\ANKIT\Anaconda\lib\site-packages\ipykernel\__main__.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\ANKIT\Anaconda\lib\site-packages\ipykernel\__main__.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\ANKIT\Anaconda\lib\site-packages\ipykernel\__main__.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty
empty

In [20]:
manager_df

,tran_ID,tran_Year,Team1,Team1_mgr,Team1_mgr_score,Team2,Team2_mgr,Team2_mgr_score
0,48198,1886,PIT,NaN,NaN,SL5,schmegu99,-6
1,48204,1887,PIT,phillho99,-60,CHN,ansonca01,297
2,48205,1887,WS8,gaffnjo99,-40,IN3,burnhwa99,-16
3,48210,1888,WS8,hewetwa99,-19,PHI,wrighha01,301
4,48212,1888,NY1,mutriji99,194,PIT,phillho99,-62
5,48220,1889,IN3,bancrfr99,40,WS8,irwinar01,-17
6,48226,1890,PHI,allenbo01,15,PIT,heckegu01,-90
7,48229,1892,LS3,chapmja01,-151,CHN,ansonca01,372
8,48230,1892,SLN,carutbo01,-16,PIT,buckeal99,-19
9,48231,1892,PIT,buckeal99,-19,BLN,hanlone01,-58
10,48232,1892,PIT,buckeal99,-19,BLN,hanlone01,-58
11,48233,1893,SLN,watkibi01,20,BSN,seleefr99,152
12,48234,1893,BRO,foutzda01,2,WSN,NaN,NaN
13,48235,1893,CL4,tebeapa01,37,NY1,wardjo01,48
14,48236,1893,NY1,wardjo01,48,PHI,wrighha01,340
15,48237,1893,PIT,buckeal99,25,WSN,NaN,NaN
16,48238,1893,BLN,hanlone01,-68,LS3,barnibi01,-105
17,48239,1893,BLN,hanlone01,-68,CIN,comisch01,319
18,48243,1893,CIN,comisch01,319,WSN,NaN,NaN
19,48244,1894,BLN,hanlone01,-18,BRO,foutzda01,11
20,48245,1894,NY1,wardjo01,92,WSN,NaN,NaN
21,48246,1894,LS3,barnibi01,-163,CHN,ansonca01,339
22,48247,1894,CL4,tebeapa01,44,BLN,hanlone01,-18
23,48248,1894,PIT,buckeal99,23,LS3,barnibi01,-163
24,48249,1894,LS3,barnibi01,-163,BLN,hanlone01,-18
25,48250,1895,LS3,mcclojo99,-61,SLN,buckeal99,5
26,48251,1895,SLN,buckeal99,5,PIT,mackco01,12
27,48252,1895,BRO,foutzda01,22,PIT,mackco01,12
28,48253,1895,SLN,buckeal99,5,BLN,hanlone01,26
29,48254,1895,PHI,irwinar01,59,BSN,seleefr99,197
...,...,...,...,...,...,...,...,...
5592,76784,2015,ARI,halech01,-4,HOU,hinchaj01,-24
5593,76786,2015,TEX,banisje01,14,BOS,farrejo03,-10
5594,76791,2015,CLE,francte01,145,ATL,gonzafr99,37
5595,76824,2015,TEX,banisje01,14,SDN,blackbu02,-64
5596,76834,2015,LAN,mattido01,83,PHI,mackape01,-14
5597,76838,2015,CIN,pricebr99,-44,SFN,bochybr01,20
5598,76849,2015,MIL,counscr01,-15,MIN,molitpa01,4
5599,76879,2015,SEA,mcclell01,-108,CHN,maddojo99,54
5600,76886,2015,NYN,collite99,-12,ARI,halech01,-4
5601,76898,2015,SEA,mcclell01,-108,CHN,maddojo99,54
5602,76900,2015,ATL,gonzafr99,37,KCA,yostne01,-46
5603,76902,2015,BOS,farrejo03,-10,SFN,bochybr01,20
5604,76904,2015,SEA,mcclell01,-108,LAN,mattido01,83
5605,76908,2015,LAN,mattido01,83,TOR,gibbojo02,14
5606,76974,2015,LAN,mattido01,83,TOR,gibbojo02,14
5607,77256,2015,TBA,cashke01,-2,SEA,mcclell01,-108
5608,77377,2015,ARI,halech01,-4,MIN,molitpa01,4
5609,77544,2015,MIN,molitpa01,4,NYA,girarjo01,168
5610,77546,2015,NYA,girarjo01,168,SDN,blackbu02,-64
5611,77554,2015,SDN,blackbu02,-64,SEA,mcclell01,-108
5612,77564,2015,ANA,NaN,NaN,ATL,gonzafr99,37
5613,77573,2015,SDN,blackbu02,-64,BOS,farrejo03,-10
5614,77576,2015,ARI,halech01,-4,PHI,mackape01,-14
5615,77582,2015,SEA,mcclell01,-108,TEX,banisje01,14
5616,77593,2015,MIL,counscr01,-15,DET,ausmubr01,5
5617,77601,2015,HOU,hinchaj01,-24,MIL,counscr01,-15
5618,77606,2015,MIL,counscr01,-15,SEA,mcclell01,-108
5619,77614,2015,DET,ausmubr01,5,ATL,gonzafr99,37
5620,77616,2015,TEX,banisje01,14,CHN,maddojo99,54
5621,77618,2015,OAK,melvibo01,24,TOR,gibbojo02,14